name: basic-calc
version: '1.0'
summary: Simple calculator for Linux
description: |
  This is a simple calculator for Linux.

grade: stable
confinement: strict

apps:
  basic-calc:
    command: Calc.py
    plugs:
      - home
    desktop: basic-calc.desktop  # Specify the desktop file

parts:
  basic-calc:
    source: .
    plugin: python
    python-version: python3
    stage-packages:
      - python3-tk  # Tkinter package

  desktop-entry:
    plugin: dump
    source: desktop-entry/
    organize:
      basic-calc.desktop: usr/share/applications/basic-calc.desktop
    after:
      - basic-calc

  desktop-icons:
    plugin: dump
    source: desktop-entry/icons/
    organize:
      icons.png: usr/share/icons/hicolor/48x48/apps/icons.png
    after:
      - desktop-entry

